import { EB_Garamond, IBM_Plex_Mono } from "next/font/google";
import "./globals.css";

const ibmPlexMono = IBM_Plex_Mono({ subsets: ["latin"], variable: '--font-ibm-plex-mono', weight: ['400'] });
const ebGaramond = EB_Garamond({ subsets: ["latin"], variable: '--font-eb-garamond', weight: ['400'] });

export const metadata = {
  title: "Portafolio - Bea",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es" className={`${ibmPlexMono.variable} ${ebGaramond.variable}`}>
      <body>{children}</body>
    </html>
  );
}

